version: "3.3"
services:
  xampp:
    ports:
      - "41061:22"
      - "41062:80"
    image: tomsik68/xampp:8
    networks:
    - passwordManager_net
    container_name: xampp
    volumes:
      - ./site:/www

  # Create database
  db:
    image: mysql
    container_name: password_manager_db
    ports:
      - "3306:3306"
    networks:
    - passwordManager_net
    environment:
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mysqldb
      MYSQL_ROOT_PASSWORD: root
    command: --init-file /data/application/init.sql
    volumes:
      - ./passwordManager.sql:/data/application/init.sql

networks:
  passwordManager_net:
    name: passwordManager_net
    driver: bridge
